apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:aeD+MA5hwDLUVt26Aqmc3qz+07mkDjlRr1fMa8cIhzU=,iv:ZVhcXM1khLDAdYZ5dw1SHoOFKK+CGXgmC7qfZLibQ58=,tag:858T6R6SBMwcZuALWdah+Q==,type:str]
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:/55DkViK4udhA2nFOxyPMjpY4a0xgLpQx2HV6nYJjxJyt4X35mzZeTX0cqfLBQZI,iv:lBWF2LXS3ErXvZlHzTG5m0GPR23+Fv3t9AxlJacdoJc=,tag:IGb/eqDEIbs54kkhvAl/Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RW1PbndPWm4xNE5DV0dF
            WW1wd3pvcXQvaEM2NUJTYzlFeEM4c3Z6ZmtVCnNvV1FEODg0ZkxpaUxJeW1pU2xl
            M2RVbXYvYmJsa1huZEQxOWpFbDFzd00KLS0tIHJqZVErUHQ2cWpwT052NjdDSWVQ
            dDltcmhkRVQra3NDNmZidHBqbHJoZk0K6fstDWX6dAIciTVu0KBWOcjjcwA16JKP
            /wjxfiBsi7VcHIpNAOforay9nkmztFpECK3wuQyXx9m2cN7fLf1OBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rectewyjyw259ks6e8epgac022665n88yf9ep64fe7kky92thgkq8tfs7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T00:54:08Z"
    mac: ENC[AES256_GCM,data:miCWQSKv39SvS+pk7ceUHsCBfx5GoGCK0B+pK0nGIGYxqVTG+KGnvVo/uTI6ZFvybAMXewZTx9KxmD2ek2ZVxCYo6uoVbMOfx2OXAzM2fKQjre4qDv1s+FabpdKLv32+atLXmL1MxaLKO3dzdh3MS9xKG4bLX+F9BhQdjkcW7Ek=,iv:v4jMn1X8uJq3hGWEXmUBtHWkHoWAY3yHChdCmpOvvSA=,tag:6sqwr9/s6qTyc9J/VIwsYg==,type:str]
    version: 3.13.2
