apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: postgres
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:CvUBEcY3Xr0=,iv:FbBkjGn1CWJe/hj2QOOOpEEwVP0jwyxRfQiWIHkx3k8=,tag:ZakYVm29WQ25L+mvEBYhmg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9/bOMWqdzG0taAEUcSTOrXBiazR+RLhlvDXo765H8Og=,iv:owDWlBdVJ7DDlkB4MzmFeRtYeQ/e1qkPEO4n9ADtbpo=,tag:gg6ag5bGyZ4ye/iLpvaAIw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:O9AOTVHDYl0=,iv:6soQdlda36BGCPiXiyrtktsC7uspREekMA6teYi6K6A=,tag:uq2Dls32U3xl98lFbp+LCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZldPeXhoSHNQYllSSkNC
            WjJrd05raTkvV1NKbVRuT3FiZWVlTDdrWEZJCjhBQ0ljcjNDR1JCZDAwNDd5cHk4
            MWZpbWl0dXZMNHRKSm9iRG9QT1ZtcjAKLS0tIGdBTkkvRGdMVHV2bmM0T3h0eHpo
            Zmtyblk0bGkyVzVZSnZxdTIvdytid2MK8Eqnp9axB1qDzzCM82schNve9pIkEWll
            Lk2L7bu1Uu2207keF5TvyQLkuwLcAoaqT/8OANThkWBwj/e7cJ7BQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rectewyjyw259ks6e8epgac022665n88yf9ep64fe7kky92thgkq8tfs7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T00:34:48Z"
    mac: ENC[AES256_GCM,data:NcpYKHGT0aVuw8vH/AGqgPKDyihM+Ddic4Q5u/ahQt5BcFc8LUax7kBVvqI8+8ZzHDH8OudPQ5Wdlja/87E84pb5h0KpzshQqHj55zEc4UTDWBB8DbHZthLcrrhXA0QPLTU7JXzCky7CLGtq6UKaZEiB4dlhaSkTuzhOZfjYSqY=,iv:idE7vYf18kS1EABb9Nmkw/c0K1oQLu/lqjZsVJQXYo8=,tag:LcoK9vyM2CpqFKMq5U1TdQ==,type:str]
    version: 3.13.2
