apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:xal4zRM=,iv:lHho/wbqvhVY2V8ukwOSHvE0uRuSLSKzg7SmWO7nSQs=,tag:zQ9WOlwPTkSv+2vUo7bTdQ==,type:str]
    admin-password: ENC[AES256_GCM,data:PsJBSlkK6YGqptAWthcPSJN6DzoktdwF,iv:4mgJ2EvZzOdfICdVxC8HXTq76tlpMEDa3qfGUb6Ug5Q=,tag:L1uCXtNnL9BwFd8/NnE7tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTm1ZWHh0UjNpMWltcjR3
            azhlQnA4ZXNhNEYwMm5yNmZMQXlSTk1LamhvCnEyT1c2V0xCTkZCakptWExPaWtH
            YWRMR0JVd2tGUGc5YVZuS2k4cDhVdU0KLS0tIGpGS2pxSmFWMmJWK05GN0haM0hs
            eldxczlPbUZldVR6RmFmNG53c3ZoNE0Kzen9ob0bU+sJDAVO9eIJOqWPGeUmrmtE
            RBgbI9qj75Ef+huu5Yi4BtTlcV/LNIHHs/3NZ4KNc0wN/RHTegkWcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rectewyjyw259ks6e8epgac022665n88yf9ep64fe7kky92thgkq8tfs7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T00:59:17Z"
    mac: ENC[AES256_GCM,data:L7L52duGSMf+cL4W8su3JzzCvt/xIpFr4x00Jp8v63RyD2CJ3/4X3SpobAfNJ/UvnSjREmln0L/F/Wh/8W3J6uLExazGowK51T25dW/+rpj7SbFWqkxsw+5oi7GZfGsIWOHfPmoaSZ0HMm0wGMizU88vVAAvHAnLSai/lXxJY9E=,iv:+Imzz4ynA41+YKWthHOeC/DaTdZBUWOX7FiSNFmQYYA=,tag:rlXI2w8++buBg5eZ+nha3A==,type:str]
    version: 3.13.2
